name: Prettier code formatter

on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Prettier and plugins
        run: |
          npm install --save-dev prettier @shopify/prettier-plugin-liquid
          cp .prettierrc ~/.prettierrc
      - name: Run Prettier
        run: npx prettier --plugin @shopify/prettier-plugin-liquid . --check
